# Generated by Django 3.2.13 on 2022-11-02 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qna', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qna',
            field=models.ManyToManyField(related_name='qna_product', to='qna.Question'),
        ),
    ]
